# Generated by Django 3.1.2 on 2020-12-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='airport',
            table='airport',
        ),
    ]
